import type { MathExpression } from "./math/schema";

export type WorkspaceKey = "lite" | "plus" | "realtime";

export interface WorkspaceConfig {
  key: WorkspaceKey;
  name: string;
  description: string;
  tier: "Free" | "Plus" | "Pro";
  defaultChannels: string[];
  mathExpressions: MathExpression[];
  activeTabs: string[];
}

export const WORKSPACES: Record<WorkspaceKey, WorkspaceConfig> = {
  lite: {
    key: "lite",
    name: "iRacing Lite Workbook v1.2",
    description: "Standard offline data layout. Covers basic traces, G-Gs, and brake bias.",
    tier: "Free",
    defaultChannels: ["Speed", "Throttle", "Brake", "RPM", "Gear", "SteeringWheelAngle"],
    activeTabs: ["cinema", "readout", "laps", "gg", "brake", "setup"],
    mathExpressions: [
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e100",
        name: "Lap Distance",
        key: "lap_distance",
        expression: "[LapDist]",
        unit: "m",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e101",
        name: "Thr/Brake/Coast",
        key: "throttle_brake_coast",
        expression: "choose(([Throttle]>98),2,choose(([Brake]>65),4,choose(([Throttle]>2)&&([Throttle]<98),1,choose(([Brake]>2)&&([Brake]<65),3,0))))",
        unit: "state",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e102",
        name: "Total Brake Pressure",
        key: "total_brake_pressure",
        expression: "[LFbrakeLinePress]+[RFbrakeLinePress]+[LRbrakeLinePress]+[RRbrakeLinePress]",
        unit: "bar",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e103",
        name: "Average LF Tyre Temp",
        key: "avg_lf_temp",
        expression: "([LFtempL]+[LFtempM]+[LFtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e104",
        name: "Average RF Tyre Temp",
        key: "avg_rf_temp",
        expression: "([RFtempL]+[RFtempM]+[RFtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e105",
        name: "Average LR Tyre Temp",
        key: "avg_lr_temp",
        expression: "([LRtempL]+[LRtempM]+[LRtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e106",
        name: "Average RR Tyre Temp",
        key: "avg_rr_temp",
        expression: "([RRtempL]+[RRtempM]+[RRtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e107",
        name: "Rear Wheel Speed Diff",
        key: "rear_speed_diff",
        expression: "[LRspeed]-[RRspeed]",
        unit: "kph",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e108",
        name: "Front Wheel Speed Diff",
        key: "front_speed_diff",
        expression: "[LFspeed]-[RFspeed]",
        unit: "kph",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e109",
        name: "Steering Angle Inverted",
        key: "steer_angle_inv",
        expression: "[SteeringWheelAngle]*(-1)",
        unit: "deg",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e110",
        name: "Yaw Rate Inverted",
        key: "yaw_rate_inv",
        expression: "[YawRate]*(-1)",
        unit: "deg/s",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e111",
        name: "Front Ride Height Avg",
        key: "front_ride_height_avg",
        expression: "([LFrideHeight]+[RFrideHeight])/2",
        unit: "mm",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e112",
        name: "Rear Ride Height Avg",
        key: "rear_ride_height_avg",
        expression: "([LRrideHeight]+[RRrideHeight])/2",
        unit: "mm",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e113",
        name: "Live Brake Bias",
        key: "live_brake_bias",
        expression: "[LFbrakeLinePress]/([LFbrakeLinePress]+[LRbrakeLinePress])*100",
        unit: "%",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  plus: {
    key: "plus",
    name: "iRacing Plus Workbook v1.3",
    description: "Expanded professional offline analysis workbook. Dampers, Scatters, and Setup Diffs.",
    tier: "Plus",
    defaultChannels: [
      "Speed",
      "Throttle",
      "Brake",
      "RPM",
      "Gear",
      "SteeringWheelAngle",
      "LFshockDefl",
      "RFshockDefl",
      "LRshockDefl",
      "RRshockDefl",
    ],
    activeTabs: [
      "cinema",
      "readout",
      "laps",
      "gg",
      "brake",
      "setup",
      "histogram",
      "scatter",
      "optimal",
      "whatif",
      "apex",
      "waterfall",
      "slip",
      "setupdiff",
    ],
    mathExpressions: [
      // Include all Lite formulas
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e100",
        name: "Lap Distance",
        key: "lap_distance",
        expression: "[LapDist]",
        unit: "m",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e101",
        name: "Thr/Brake/Coast",
        key: "throttle_brake_coast",
        expression: "choose(([Throttle]>98),2,choose(([Brake]>65),4,choose(([Throttle]>2)&&([Throttle]<98),1,choose(([Brake]>2)&&([Brake]<65),3,0))))",
        unit: "state",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e102",
        name: "Total Brake Pressure",
        key: "total_brake_pressure",
        expression: "[LFbrakeLinePress]+[RFbrakeLinePress]+[LRbrakeLinePress]+[RRbrakeLinePress]",
        unit: "bar",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e103",
        name: "Average LF Tyre Temp",
        key: "avg_lf_temp",
        expression: "([LFtempL]+[LFtempM]+[LFtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e104",
        name: "Average RF Tyre Temp",
        key: "avg_rf_temp",
        expression: "([RFtempL]+[RFtempM]+[RFtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e105",
        name: "Average LR Tyre Temp",
        key: "avg_lr_temp",
        expression: "([LRtempL]+[LRtempM]+[LRtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e106",
        name: "Average RR Tyre Temp",
        key: "avg_rr_temp",
        expression: "([RRtempL]+[RRtempM]+[RRtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e107",
        name: "Rear Wheel Speed Diff",
        key: "rear_speed_diff",
        expression: "[LRspeed]-[RRspeed]",
        unit: "kph",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e108",
        name: "Front Wheel Speed Diff",
        key: "front_speed_diff",
        expression: "[LFspeed]-[RFspeed]",
        unit: "kph",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e109",
        name: "Steering Angle Inverted",
        key: "steer_angle_inv",
        expression: "[SteeringWheelAngle]*(-1)",
        unit: "deg",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e110",
        name: "Yaw Rate Inverted",
        key: "yaw_rate_inv",
        expression: "[YawRate]*(-1)",
        unit: "deg/s",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e111",
        name: "Front Ride Height Avg",
        key: "front_ride_height_avg",
        expression: "([LFrideHeight]+[RFrideHeight])/2",
        unit: "mm",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e112",
        name: "Rear Ride Height Avg",
        key: "rear_ride_height_avg",
        expression: "([LRrideHeight]+[RRrideHeight])/2",
        unit: "mm",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e113",
        name: "Live Brake Bias",
        key: "live_brake_bias",
        expression: "[LFbrakeLinePress]/([LFbrakeLinePress]+[LRbrakeLinePress])*100",
        unit: "%",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      // Plus specific formulas
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e120",
        name: "G Total (Vector)",
        key: "g_total",
        expression: "sqrt(([Accel Lateral]*[Accel Lateral])+([Accel Longitudinal]*[Accel Longitudinal]))",
        unit: "G",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e121",
        name: "Yaw Gain",
        key: "yaw_gain",
        expression: "[YawRate]/[SteeringWheelAngle]",
        unit: "ratio",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e122",
        name: "Longitudinal Slip",
        key: "longitudinal_slip",
        expression: "100*((0.5*([LFspeed]+[RFspeed]))/(0.5*([LRspeed]+[RRspeed]))-1)",
        unit: "%",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e123",
        name: "Pedal Overlap Detection",
        key: "pedal_overlap",
        expression: "choose(([Throttle]>2.5)&&([Brake]>2.5),1,0)",
        unit: "flag",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e124",
        name: "Inverse Track Curvature",
        key: "inverse_curvature",
        expression: "abs(([Accel Lateral]/([Speed]*[Speed])))",
        unit: "1/m",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e125",
        name: "Speed Adjusted Steering",
        key: "speed_adj_steer",
        expression: "[SteeringWheelAngle]*([Speed]*sqrt([Speed]))",
        unit: "deg-mps",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e126",
        name: "Corner State Machine",
        key: "corner_state",
        expression: "choose(([Brake]>20)&&([Accel Longitudinal]<-0.3),3,choose(([Throttle]>30)&&(abs([Accel Lateral])>0.5),5,choose((abs([Accel Lateral])>0.5),1,0)))",
        unit: "state",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  realtime: {
    key: "realtime",
    name: "iRacing Plus Real-Time Workbook v1.0",
    description: "Full pro-tier workspace. Integrates high-frequency active math, 3D overlays, and spider trackers.",
    tier: "Pro",
    defaultChannels: [
      "Speed",
      "Throttle",
      "Brake",
      "RPM",
      "Gear",
      "SteeringWheelAngle",
      "LFshockDefl",
      "RFshockDefl",
      "LRshockDefl",
      "RRshockDefl",
      "YawRate",
    ],
    activeTabs: [
      "cinema",
      "readout",
      "laps",
      "gg",
      "brake",
      "setup",
      "histogram",
      "scatter",
      "optimal",
      "whatif",
      "apex",
      "waterfall",
      "slip",
      "setupdiff",
      "replay3d",
      "piano",
      "spider",
    ],
    mathExpressions: [
      // Includes all Plus formulas + Real-time active math
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e100",
        name: "Lap Distance",
        key: "lap_distance",
        expression: "[LapDist]",
        unit: "m",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e101",
        name: "Thr/Brake/Coast",
        key: "throttle_brake_coast",
        expression: "choose(([Throttle]>98),2,choose(([Brake]>65),4,choose(([Throttle]>2)&&([Throttle]<98),1,choose(([Brake]>2)&&([Brake]<65),3,0))))",
        unit: "state",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e102",
        name: "Total Brake Pressure",
        key: "total_brake_pressure",
        expression: "[LFbrakeLinePress]+[RFbrakeLinePress]+[LRbrakeLinePress]+[RRbrakeLinePress]",
        unit: "bar",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e103",
        name: "Average LF Tyre Temp",
        key: "avg_lf_temp",
        expression: "([LFtempL]+[LFtempM]+[LFtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e104",
        name: "Average RF Tyre Temp",
        key: "avg_rf_temp",
        expression: "([RFtempL]+[RFtempM]+[RFtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e105",
        name: "Average LR Tyre Temp",
        key: "avg_lr_temp",
        expression: "([LRtempL]+[LRtempM]+[LRtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e106",
        name: "Average RR Tyre Temp",
        key: "avg_rr_temp",
        expression: "([RRtempL]+[RRtempM]+[RRtempR])/3",
        unit: "C",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e107",
        name: "Rear Wheel Speed Diff",
        key: "rear_speed_diff",
        expression: "[LRspeed]-[RRspeed]",
        unit: "kph",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e108",
        name: "Front Wheel Speed Diff",
        key: "front_speed_diff",
        expression: "[LFspeed]-[RFspeed]",
        unit: "kph",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e109",
        name: "Steering Angle Inverted",
        key: "steer_angle_inv",
        expression: "[SteeringWheelAngle]*(-1)",
        unit: "deg",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e110",
        name: "Yaw Rate Inverted",
        key: "yaw_rate_inv",
        expression: "[YawRate]*(-1)",
        unit: "deg/s",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e111",
        name: "Front Ride Height Avg",
        key: "front_ride_height_avg",
        expression: "([LFrideHeight]+[RFrideHeight])/2",
        unit: "mm",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e112",
        name: "Rear Ride Height Avg",
        key: "rear_ride_height_avg",
        expression: "([LRrideHeight]+[RRrideHeight])/2",
        unit: "mm",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e113",
        name: "Live Brake Bias",
        key: "live_brake_bias",
        expression: "[LFbrakeLinePress]/([LFbrakeLinePress]+[LRbrakeLinePress])*100",
        unit: "%",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e120",
        name: "G Total (Vector)",
        key: "g_total",
        expression: "sqrt(([Accel Lateral]*[Accel Lateral])+([Accel Longitudinal]*[Accel Longitudinal]))",
        unit: "G",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e121",
        name: "Yaw Gain",
        key: "yaw_gain",
        expression: "[YawRate]/[SteeringWheelAngle]",
        unit: "ratio",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e122",
        name: "Longitudinal Slip",
        key: "longitudinal_slip",
        expression: "100*((0.5*([LFspeed]+[RFspeed]))/(0.5*([LRspeed]+[RRspeed]))-1)",
        unit: "%",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e123",
        name: "Pedal Overlap Detection",
        key: "pedal_overlap",
        expression: "choose(([Throttle]>2.5)&&([Brake]>2.5),1,0)",
        unit: "flag",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e124",
        name: "Inverse Track Curvature",
        key: "inverse_curvature",
        expression: "abs(([Accel Lateral]/([Speed]*[Speed])))",
        unit: "1/m",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      // Real-time exclusive triggers
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e130",
        name: "WheelLockLF",
        key: "wheellock_lf",
        expression: "choose((([Speed]-[LFspeed])>10)&&([Brake]>20),1,0)",
        unit: "flag",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e131",
        name: "WheelLockRF",
        key: "wheellock_rf",
        expression: "choose((([Speed]-[RFspeed])>10&&[Brake]>20),1,0)",
        unit: "flag",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "d04a6011-e4f0-4d4e-bba3-5d803836e132",
        name: "WheelLockGlobal",
        key: "wheellock_global",
        expression: "choose(([Speed]-[LFspeed]>10)||([Speed]-[RFspeed]>10),1,0)",
        unit: "flag",
        enabled: true,
        scope: "both",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
};
