/**
 * Curated catalog of canonical iRacing telemetry channels, modeled on the
 * channel list shipped with the McLaren ATLAS iRacing plugin workbook.
 *
 * Used by the ChannelBrowser to (a) pin the most useful channels to the top
 * in an "Essentials" group, (b) regroup raw channels into ATLAS-style
 * categories that are friendlier than our regex inferGroup, and (c) show a
 * short description tooltip explaining each channel.
 */

export type CatalogEntry = {
  /** Exact iRacing channel name (case-sensitive). */
  name: string;
  /** ATLAS-style group label. */
  group: string;
  /** One-line human description. */
  desc: string;
  /** Whether to surface in the "Essentials" pinned section. */
  essential?: boolean;
};

export const CHANNEL_CATALOG: CatalogEntry[] = [
  // Driver inputs
  { name: "Throttle", group: "Driver Inputs", desc: "Throttle pedal 0–1", essential: true },
  { name: "Brake", group: "Driver Inputs", desc: "Brake pedal 0–1", essential: true },
  { name: "Clutch", group: "Driver Inputs", desc: "Clutch pedal 0–1 (1 = engaged)" },
  { name: "SteeringWheelAngle", group: "Driver Inputs", desc: "Steering angle, radians (+ left)", essential: true },
  { name: "SteeringWheelAngleMax", group: "Driver Inputs", desc: "Max steering lock (rad)" },
  { name: "SteeringWheelTorque", group: "Driver Inputs", desc: "Wheel torque feedback (Nm)" },
  { name: "SteeringWheelPctTorque", group: "Driver Inputs", desc: "Wheel torque % of max" },
  { name: "SteeringWheelPctTorqueSign", group: "Driver Inputs", desc: "Signed torque % (sign = direction)" },
  { name: "SteeringWheelPctIntensity", group: "Driver Inputs", desc: "FFB intensity %" },
  { name: "SteeringWheelPctSmoothing", group: "Driver Inputs", desc: "FFB smoothing %" },
  { name: "SteeringWheelPctDamper", group: "Driver Inputs", desc: "FFB damper %" },
  { name: "SteeringWheelLimiter", group: "Driver Inputs", desc: "Wheel torque clipping flag" },
  { name: "SteeringWheelMaxForceNm", group: "Driver Inputs", desc: "FFB strength setting (Nm)" },
  { name: "SteeringWheelPeakForceNm", group: "Driver Inputs", desc: "Peak torque seen (Nm)" },
  { name: "SteeringWheelUseLinear", group: "Driver Inputs", desc: "Linear FFB mode flag" },
  { name: "HandbrakeRaw", group: "Driver Inputs", desc: "Raw handbrake input 0–1" },
  { name: "BrakeABSactive", group: "Driver Inputs", desc: "ABS active flag" },
  { name: "ThrottleRaw", group: "Driver Inputs", desc: "Raw throttle input 0–1" },
  { name: "ClutchRaw", group: "Driver Inputs", desc: "Raw clutch input 0–1" },
  { name: "dcStarter", group: "Driver Inputs", desc: "Starter button" },
  { name: "dcPitSpeedLimiterToggle", group: "Driver Inputs", desc: "Pit speed limiter toggle" },
  { name: "dcLaunchRPM", group: "Driver Inputs", desc: "Launch RPM setting" },
  { name: "dcTractionControl", group: "Driver Inputs", desc: "Traction control setting" },
  { name: "dcTractionControl2", group: "Driver Inputs", desc: "Traction control 2 setting" },
  { name: "dcABS", group: "Driver Inputs", desc: "ABS setting" },
  { name: "dcAntiRollFront", group: "Driver Inputs", desc: "Front anti-roll bar setting" },
  { name: "dcAntiRollRear", group: "Driver Inputs", desc: "Rear anti-roll bar setting" },
  { name: "dcDiffEntry", group: "Driver Inputs", desc: "Diff entry setting" },
  { name: "dcDiffMiddle", group: "Driver Inputs", desc: "Diff middle setting" },
  { name: "dcDiffExit", group: "Driver Inputs", desc: "Diff exit setting" },
  { name: "dcThrottleShape", group: "Driver Inputs", desc: "Throttle map setting" },
  { name: "dcEnginePower", group: "Driver Inputs", desc: "Engine power map" },
  { name: "dcMGUKDeployMode", group: "Driver Inputs", desc: "MGU-K deploy mode" },
  { name: "dcMGUKDeployFixed", group: "Driver Inputs", desc: "MGU-K fixed deploy" },
  { name: "dcMGUKRegenGain", group: "Driver Inputs", desc: "MGU-K regen gain" },
  // Vehicle
  { name: "Speed", group: "Vehicle", desc: "Ground speed (m/s)", essential: true },
  { name: "RPM", group: "Vehicle", desc: "Engine RPM", essential: true },
  { name: "Gear", group: "Vehicle", desc: "Current gear", essential: true },
  { name: "VelocityX", group: "Vehicle", desc: "Body-frame longitudinal velocity (m/s)" },
  { name: "VelocityY", group: "Vehicle", desc: "Body-frame lateral velocity (m/s)" },
  { name: "VelocityZ", group: "Vehicle", desc: "Body-frame vertical velocity (m/s)" },
  { name: "YawRate", group: "Vehicle", desc: "Yaw rate (rad/s)" },
  { name: "RollRate", group: "Vehicle", desc: "Roll rate (rad/s)" },
  { name: "PitchRate", group: "Vehicle", desc: "Pitch rate (rad/s)" },
  { name: "LatAccel", group: "Vehicle", desc: "Lateral g (corner load)", essential: true },
  { name: "LongAccel", group: "Vehicle", desc: "Longitudinal g (brake/accel)", essential: true },
  { name: "VertAccel", group: "Vehicle", desc: "Vertical g (bumps/curbs)" },
  { name: "Roll", group: "Vehicle", desc: "Body roll angle (rad)" },
  { name: "Pitch", group: "Vehicle", desc: "Body pitch angle (rad)" },
  { name: "Yaw", group: "Vehicle", desc: "Yaw heading (rad)" },
  { name: "YawNorth", group: "Vehicle", desc: "Heading vs north (rad)" },
  { name: "Alt", group: "Vehicle", desc: "Altitude (m)" },
  { name: "Lat", group: "Vehicle", desc: "Latitude (deg)" },
  { name: "Lon", group: "Vehicle", desc: "Longitude (deg)" },
  { name: "ShiftIndicatorPct", group: "Vehicle", desc: "Shift light indicator (0–1)" },
  { name: "ShiftPowerPct", group: "Vehicle", desc: "Power band % at current RPM" },
  { name: "ShiftGrindRPM", group: "Vehicle", desc: "RPM at which gear grinds" },
  // Session / lap
  { name: "Lap", group: "Session", desc: "Current lap number", essential: true },
  { name: "LapDistPct", group: "Session", desc: "Lap progress 0–1", essential: true },
  { name: "LapDist", group: "Session", desc: "Lap distance (m)" },
  { name: "LapCurrentLapTime", group: "Session", desc: "Elapsed time on current lap (s)" },
  { name: "LapLastLapTime", group: "Session", desc: "Previous completed lap time (s)" },
  { name: "LapBestLapTime", group: "Session", desc: "Session best lap time (s)" },
  { name: "LapDeltaToBestLap", group: "Session", desc: "Δ vs personal best lap (s)" },
  { name: "LapDeltaToBestLap_DD", group: "Session", desc: "Δ-best derivative (s/s)" },
  { name: "LapDeltaToOptimalLap", group: "Session", desc: "Δ vs optimal lap (s)" },
  { name: "LapDeltaToSessionBestLap", group: "Session", desc: "Δ vs session best (s)" },
  { name: "LapDeltaToSessionLastlLap", group: "Session", desc: "Δ vs session last lap (s)" },
  { name: "LapDeltaToSessionOptimalLap", group: "Session", desc: "Δ vs session optimal (s)" },
  { name: "LapLasNLapSeq", group: "Session", desc: "Last N laps sequence id" },
  { name: "LapLastNLapTime", group: "Session", desc: "Last N-lap average (s)" },
  { name: "LapBestNLapLap", group: "Session", desc: "Lap of best N-lap stint" },
  { name: "LapBestNLapTime", group: "Session", desc: "Best N-lap average (s)" },
  { name: "LapCompleted", group: "Session", desc: "Laps completed counter" },
  { name: "RaceLaps", group: "Session", desc: "Race laps counter" },
  { name: "SessionTime", group: "Session", desc: "Session clock (s)" },
  { name: "SessionTick", group: "Session", desc: "Session tick counter" },
  { name: "SessionNum", group: "Session", desc: "Session number" },
  { name: "SessionState", group: "Session", desc: "Session state enum" },
  { name: "SessionUniqueID", group: "Session", desc: "Unique session id" },
  { name: "SessionFlags", group: "Session", desc: "Active session flags bitmap" },
  { name: "SessionLapsRemain", group: "Session", desc: "Laps remaining" },
  { name: "SessionLapsRemainEx", group: "Session", desc: "Laps remaining (incl. current)" },
  { name: "SessionLapsTotal", group: "Session", desc: "Total laps in session" },
  { name: "SessionTimeRemain", group: "Session", desc: "Time remaining (s)" },
  { name: "SessionTimeTotal", group: "Session", desc: "Total session time (s)" },
  { name: "SessionTimeOfDay", group: "Session", desc: "Sim time of day (s)" },
  { name: "PlayerCarMyIncidentCount", group: "Session", desc: "Driver's incident count" },
  { name: "PlayerCarTeamIncidentCount", group: "Session", desc: "Team incident count" },
  { name: "PlayerCarDriverIncidentCount", group: "Session", desc: "Current driver incident count" },
  { name: "PlayerCarPosition", group: "Session", desc: "Race position" },
  { name: "PlayerCarClassPosition", group: "Session", desc: "Class position" },
  { name: "PlayerCarPowerAdjust", group: "Session", desc: "BoP power adjust %" },
  { name: "PlayerCarWeightPenalty", group: "Session", desc: "BoP weight penalty (kg)" },
  { name: "PlayerCarTowTime", group: "Session", desc: "Tow time remaining (s)" },
  { name: "OnPitRoad", group: "Session", desc: "On pit road flag" },
  { name: "PitsOpen", group: "Session", desc: "Pit lane open flag" },
  { name: "PitstopActive", group: "Session", desc: "Pit stop in progress" },
  { name: "PitRepairLeft", group: "Session", desc: "Repair time left (s)" },
  { name: "PitOptRepairLeft", group: "Session", desc: "Optional repair time left (s)" },
  { name: "PitSvFlags", group: "Session", desc: "Pit service flags bitmap" },
  { name: "PitSvFuel", group: "Session", desc: "Pit service fuel target (L)" },
  { name: "PitSvLFP", group: "Session", desc: "Pit service LF pressure (kPa)" },
  { name: "PitSvRFP", group: "Session", desc: "Pit service RF pressure (kPa)" },
  { name: "PitSvLRP", group: "Session", desc: "Pit service LR pressure (kPa)" },
  { name: "PitSvRRP", group: "Session", desc: "Pit service RR pressure (kPa)" },
  { name: "IsOnTrack", group: "Session", desc: "Driver on-track flag" },
  { name: "IsOnTrackCar", group: "Session", desc: "Car on-track flag" },
  { name: "IsInGarage", group: "Session", desc: "In garage flag" },
  { name: "IsReplayPlaying", group: "Session", desc: "Replay active flag" },
  { name: "ReplayFrameNum", group: "Session", desc: "Replay frame index" },
  { name: "ReplayFrameNumEnd", group: "Session", desc: "Replay last frame index" },
  { name: "ReplayPlaySpeed", group: "Session", desc: "Replay playback speed" },
  { name: "ReplayPlaySlowMotion", group: "Session", desc: "Replay slow-mo flag" },
  { name: "ReplaySessionNum", group: "Session", desc: "Replay session id" },
  { name: "ReplaySessionTime", group: "Session", desc: "Replay session time (s)" },
  // Engine / fuel
  { name: "FuelLevel", group: "Engine", desc: "Fuel remaining (L)", essential: true },
  { name: "FuelLevelPct", group: "Engine", desc: "Fuel remaining % of tank" },
  { name: "FuelUsePerHour", group: "Engine", desc: "Instantaneous fuel use (kg/hr)" },
  { name: "FuelPress", group: "Engine", desc: "Fuel rail pressure (bar)" },
  { name: "OilTemp", group: "Engine", desc: "Engine oil temp (°C)" },
  { name: "OilPress", group: "Engine", desc: "Engine oil pressure (bar)" },
  { name: "OilLevel", group: "Engine", desc: "Engine oil level (L)" },
  { name: "WaterTemp", group: "Engine", desc: "Coolant temp (°C)" },
  { name: "WaterLevel", group: "Engine", desc: "Coolant level (L)" },
  { name: "ManifoldPress", group: "Engine", desc: "Intake manifold pressure (bar)" },
  { name: "Voltage", group: "Engine", desc: "Battery voltage (V)" },
  { name: "EngineWarnings", group: "Engine", desc: "Engine warning flag bitmap" },
  { name: "PowerMGU_K", group: "Engine", desc: "MGU-K power (W)" },
  { name: "PowerMGU_H", group: "Engine", desc: "MGU-H power (W)" },
  { name: "EnergyBatteryToMGU_KLap", group: "Engine", desc: "Battery→MGU-K energy this lap (J)" },
  { name: "EnergyERSBatteryPct", group: "Engine", desc: "ERS battery state of charge %" },
  { name: "DRS_Status", group: "Engine", desc: "DRS state enum" },
  { name: "P2P_Count", group: "Engine", desc: "Push-to-pass uses left" },
  { name: "P2P_Status", group: "Engine", desc: "Push-to-pass active" },
  // Tyres
  { name: "LFtempCM", group: "Tyres", desc: "LF carcass middle temp (°C)" },
  { name: "LFtempCL", group: "Tyres", desc: "LF carcass inner temp (°C)" },
  { name: "LFtempCR", group: "Tyres", desc: "LF carcass outer temp (°C)" },
  { name: "RFtempCM", group: "Tyres", desc: "RF carcass middle temp (°C)" },
  { name: "RFtempCL", group: "Tyres", desc: "RF carcass inner temp (°C)" },
  { name: "RFtempCR", group: "Tyres", desc: "RF carcass outer temp (°C)" },
  { name: "LRtempCM", group: "Tyres", desc: "LR carcass middle temp (°C)" },
  { name: "LRtempCL", group: "Tyres", desc: "LR carcass inner temp (°C)" },
  { name: "LRtempCR", group: "Tyres", desc: "LR carcass outer temp (°C)" },
  { name: "RRtempCM", group: "Tyres", desc: "RR carcass middle temp (°C)" },
  { name: "RRtempCL", group: "Tyres", desc: "RR carcass inner temp (°C)" },
  { name: "RRtempCR", group: "Tyres", desc: "RR carcass outer temp (°C)" },
  { name: "LFpressure", group: "Tyres", desc: "LF cold pressure (kPa)" },
  { name: "RFpressure", group: "Tyres", desc: "RF cold pressure (kPa)" },
  { name: "LRpressure", group: "Tyres", desc: "LR cold pressure (kPa)" },
  { name: "RRpressure", group: "Tyres", desc: "RR cold pressure (kPa)" },
  { name: "LFwearM", group: "Tyres", desc: "LF tread wear middle %" },
  { name: "LFwearL", group: "Tyres", desc: "LF tread wear inner %" },
  { name: "LFwearR", group: "Tyres", desc: "LF tread wear outer %" },
  { name: "RFwearM", group: "Tyres", desc: "RF tread wear middle %" },
  { name: "RFwearL", group: "Tyres", desc: "RF tread wear inner %" },
  { name: "RFwearR", group: "Tyres", desc: "RF tread wear outer %" },
  { name: "LRwearM", group: "Tyres", desc: "LR tread wear middle %" },
  { name: "LRwearL", group: "Tyres", desc: "LR tread wear inner %" },
  { name: "LRwearR", group: "Tyres", desc: "LR tread wear outer %" },
  { name: "RRwearM", group: "Tyres", desc: "RR tread wear middle %" },
  { name: "RRwearL", group: "Tyres", desc: "RR tread wear inner %" },
  { name: "RRwearR", group: "Tyres", desc: "RR tread wear outer %" },
  { name: "LFspeed", group: "Tyres", desc: "LF wheel ground speed (m/s)" },
  { name: "RFspeed", group: "Tyres", desc: "RF wheel ground speed (m/s)" },
  { name: "LRspeed", group: "Tyres", desc: "LR wheel ground speed (m/s)" },
  { name: "RRspeed", group: "Tyres", desc: "RR wheel ground speed (m/s)" },
  // Brakes
  { name: "BrakeRaw", group: "Brakes", desc: "Raw brake input 0–1" },
  { name: "dcBrakeBias", group: "Brakes", desc: "Brake bias % front" },
  { name: "LFbrakeLinePress", group: "Brakes", desc: "LF brake line pressure (bar)" },
  { name: "RFbrakeLinePress", group: "Brakes", desc: "RF brake line pressure (bar)" },
  { name: "LRbrakeLinePress", group: "Brakes", desc: "LR brake line pressure (bar)" },
  { name: "RRbrakeLinePress", group: "Brakes", desc: "RR brake line pressure (bar)" },
  { name: "LFbrakeTemp", group: "Brakes", desc: "LF brake disc temp (°C)" },
  { name: "RFbrakeTemp", group: "Brakes", desc: "RF brake disc temp (°C)" },
  { name: "LRbrakeTemp", group: "Brakes", desc: "LR brake disc temp (°C)" },
  { name: "RRbrakeTemp", group: "Brakes", desc: "RR brake disc temp (°C)" },
  // Suspension
  { name: "LFshockDefl", group: "Suspension", desc: "LF damper deflection (m)" },
  { name: "RFshockDefl", group: "Suspension", desc: "RF damper deflection (m)" },
  { name: "LRshockDefl", group: "Suspension", desc: "LR damper deflection (m)" },
  { name: "RRshockDefl", group: "Suspension", desc: "RR damper deflection (m)" },
  { name: "LFshockVel", group: "Suspension", desc: "LF damper velocity (m/s)" },
  { name: "RFshockVel", group: "Suspension", desc: "RF damper velocity (m/s)" },
  { name: "LRshockVel", group: "Suspension", desc: "LR damper velocity (m/s)" },
  { name: "RRshockVel", group: "Suspension", desc: "RR damper velocity (m/s)" },
  { name: "LFrideHeight", group: "Suspension", desc: "LF ride height (m)" },
  { name: "RFrideHeight", group: "Suspension", desc: "RF ride height (m)" },
  { name: "LRrideHeight", group: "Suspension", desc: "LR ride height (m)" },
  { name: "RRrideHeight", group: "Suspension", desc: "RR ride height (m)" },
  { name: "CFshockDefl", group: "Suspension", desc: "Centre damper deflection (m)" },
  { name: "CRshockDefl", group: "Suspension", desc: "Centre rear damper deflection (m)" },
  { name: "LFshockDefl_ST", group: "Suspension", desc: "LF damper defl (sub-tick)" },
  { name: "RFshockDefl_ST", group: "Suspension", desc: "RF damper defl (sub-tick)" },
  // Environment
  { name: "TrackTempCrew", group: "Environment", desc: "Track surface temp (°C)" },
  { name: "AirTemp", group: "Environment", desc: "Ambient air temp (°C)" },
  { name: "AirPressure", group: "Environment", desc: "Ambient air pressure (Hg)" },
  { name: "AirDensity", group: "Environment", desc: "Air density (kg/m³)" },
  { name: "RelativeHumidity", group: "Environment", desc: "Relative humidity (0–1)" },
  { name: "WindVel", group: "Environment", desc: "Wind speed (m/s)" },
  { name: "WindDir", group: "Environment", desc: "Wind direction (rad)" },
  { name: "Skies", group: "Environment", desc: "Sky cover (0=clear, 3=overcast)" },
  { name: "FogLevel", group: "Environment", desc: "Fog density (0–1)" },
  { name: "TrackWetness", group: "Environment", desc: "Track wetness enum" },
  { name: "Precipitation", group: "Environment", desc: "Precipitation rate" },
  { name: "SolarAltitude", group: "Environment", desc: "Sun altitude (rad)" },
  { name: "SolarAzimuth", group: "Environment", desc: "Sun azimuth (rad)" },
];

const BY_NAME = new Map<string, CatalogEntry>(CHANNEL_CATALOG.map((c) => [c.name, c]));

/** Look up curated metadata for a channel name (or null). */
export function catalogEntry(name: string): CatalogEntry | null {
  return BY_NAME.get(name) ?? null;
}

/** Names of essential channels in catalog order. */
export const ESSENTIAL_CHANNELS: string[] = CHANNEL_CATALOG.filter((c) => c.essential).map((c) => c.name);

/**
 * Short human-friendly description of an ATLAS-style group, shown as a hint
 * under the group header in the channel browser.
 */
export const GROUP_DESCRIPTIONS: Record<string, string> = {
  Essentials: "Pinned high-signal channels — start here.",
  "Driver Inputs": "Pedals, wheel, FFB, in-car adjusters.",
  Vehicle: "Body motion: speed, accel, attitude, GPS.",
  Session: "Lap, session clock, flags, replay, pit state.",
  Engine: "Powertrain: fuel, oil, water, ERS, DRS.",
  Tyres: "Per-corner temps, pressures, wear, wheel speeds.",
  Brakes: "Pedal, bias, line pressures, disc temps.",
  Suspension: "Damper deflection/velocity, ride heights.",
  Environment: "Track + weather conditions.",
};