/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FingerprintRouteImport } from './routes/fingerprint'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiEngineerRouteImport } from './routes/ai-engineer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as LabLapfileRouteImport } from './routes/lab.lapfile'
import { Route as DetachedInstrumentRouteImport } from './routes/detached.$instrument'
import { Route as ApiPublicOgShareTokenRouteImport } from './routes/api/public/og/share.$token'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintRoute = FingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEngineerRoute = AiEngineerRouteImport.update({
  id: '/ai-engineer',
  path: '/ai-engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLapfileRoute = LabLapfileRouteImport.update({
  id: '/lab/lapfile',
  path: '/lab/lapfile',
  getParentRoute: () => rootRouteImport,
} as any)
const DetachedInstrumentRoute = DetachedInstrumentRouteImport.update({
  id: '/detached/$instrument',
  path: '/detached/$instrument',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgShareTokenRoute = ApiPublicOgShareTokenRouteImport.update({
  id: '/api/public/og/share/$token',
  path: '/api/public/og/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-engineer': typeof AiEngineerRoute
  '/auth': typeof AuthRoute
  '/fingerprint': typeof FingerprintRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/detached/$instrument': typeof DetachedInstrumentRoute
  '/lab/lapfile': typeof LabLapfileRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/public/og/share/$token': typeof ApiPublicOgShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-engineer': typeof AiEngineerRoute
  '/auth': typeof AuthRoute
  '/fingerprint': typeof FingerprintRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/detached/$instrument': typeof DetachedInstrumentRoute
  '/lab/lapfile': typeof LabLapfileRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sessions': typeof SessionsIndexRoute
  '/api/public/og/share/$token': typeof ApiPublicOgShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-engineer': typeof AiEngineerRoute
  '/auth': typeof AuthRoute
  '/fingerprint': typeof FingerprintRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/detached/$instrument': typeof DetachedInstrumentRoute
  '/lab/lapfile': typeof LabLapfileRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/sessions/': typeof SessionsIndexRoute
  '/api/public/og/share/$token': typeof ApiPublicOgShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-engineer'
    | '/auth'
    | '/fingerprint'
    | '/how-it-works'
    | '/live'
    | '/roadmap'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/detached/$instrument'
    | '/lab/lapfile'
    | '/sessions/$id'
    | '/share/$token'
    | '/sessions/'
    | '/api/public/og/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-engineer'
    | '/auth'
    | '/fingerprint'
    | '/how-it-works'
    | '/live'
    | '/roadmap'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/detached/$instrument'
    | '/lab/lapfile'
    | '/sessions/$id'
    | '/share/$token'
    | '/sessions'
    | '/api/public/og/share/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-engineer'
    | '/auth'
    | '/fingerprint'
    | '/how-it-works'
    | '/live'
    | '/roadmap'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/detached/$instrument'
    | '/lab/lapfile'
    | '/sessions/$id'
    | '/share/$token'
    | '/sessions/'
    | '/api/public/og/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiEngineerRoute: typeof AiEngineerRoute
  AuthRoute: typeof AuthRoute
  FingerprintRoute: typeof FingerprintRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LiveRoute: typeof LiveRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  DetachedInstrumentRoute: typeof DetachedInstrumentRoute
  LabLapfileRoute: typeof LabLapfileRoute
  SessionsIdRoute: typeof SessionsIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  ApiPublicOgShareTokenRoute: typeof ApiPublicOgShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprint': {
      id: '/fingerprint'
      path: '/fingerprint'
      fullPath: '/fingerprint'
      preLoaderRoute: typeof FingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-engineer': {
      id: '/ai-engineer'
      path: '/ai-engineer'
      fullPath: '/ai-engineer'
      preLoaderRoute: typeof AiEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/lapfile': {
      id: '/lab/lapfile'
      path: '/lab/lapfile'
      fullPath: '/lab/lapfile'
      preLoaderRoute: typeof LabLapfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detached/$instrument': {
      id: '/detached/$instrument'
      path: '/detached/$instrument'
      fullPath: '/detached/$instrument'
      preLoaderRoute: typeof DetachedInstrumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/share/$token': {
      id: '/api/public/og/share/$token'
      path: '/api/public/og/share/$token'
      fullPath: '/api/public/og/share/$token'
      preLoaderRoute: typeof ApiPublicOgShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiEngineerRoute: AiEngineerRoute,
  AuthRoute: AuthRoute,
  FingerprintRoute: FingerprintRoute,
  HowItWorksRoute: HowItWorksRoute,
  LiveRoute: LiveRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  DetachedInstrumentRoute: DetachedInstrumentRoute,
  LabLapfileRoute: LabLapfileRoute,
  SessionsIdRoute: SessionsIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  ApiPublicOgShareTokenRoute: ApiPublicOgShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
